const skillBadgeList = [
    "Create and Manage Cloud Spanner Instances",
    "Get Started with Eventarc",
    "Create and Manage Cloud SQL for PostgreSQL Instances",
    "Prepare Data for ML APIs on Google Cloud",
    "Engineer Data for Predictive Modeling with BigQuery ML",
    "Build a Data Warehouse with BigQuery",
    "Create ML Models with BigQuery ML",
    "Tag and Discover BigLake Data",
    "Share Data Using Google Data Cloud",
    "Monitor Environments with Google Cloud Managed Service for Prometheus",
    "Develop and Secure APIs with Apigee X",
    "Build a Secure Google Cloud Network",
    "App Engine: 3 Ways",
    "Build LookML Objects in Looker",
    "Deploy and Manage Apigee X",
    "Implement DevOps Workflows in Google Cloud",
    "Manage Data Models in Looker",
    "Protect Cloud Traffic with Chrome Enterprise Premium Security",
    "Get Started with Sensitive Data Protection",
    "Streaming Analytics into BigQuery",
    "Build Real World AI Applications with Gemini and Imagen",
    "The Basics of Google Cloud Compute",
    "Analyze Images with the Cloud Vision API",
    "Develop Serverless Apps with Firebase",
    "Develop with Apps Script and AppSheet",
    "Build and Deploy Machine Learning Solutions on Vertex AI",
    "Secure Software Delivery",
    "Derive Insights from BigQuery Data",
    "Set Up a Google Cloud Network",
    "Automate Data Capture at Scale with Document AI",
    "Deploy Kubernetes Applications on Google Cloud",
    "Build Custom Processors with Document AI",
    "Classify Images with TensorFlow on Google Cloud",
    "Perform Predictive Data Analysis in BigQuery",
    "Develop Serverless Applications on Cloud Run",
    "Detect Manufacturing Defects using Visual Inspection AI",
    "Create a Secure Data Lake on Cloud Storage",
    "Prepare Data for Looker Dashboards and Reports",
    "Secure BigLake Data",
    "Build a Website on Google Cloud",
    "Get Started with Google Workspace Tools",
    "Optimize Costs for Google Kubernetes Engine",
    "Get Started with Dataplex",
    "Get Started with Pub/Sub",
    "Cloud Functions: 3 Ways",
    "Use Functions, Formulas, and Charts in Google Sheets",
    "Cloud Architecture: Design, Implement, and Manage",
    "Using the Google Cloud Speech API",
    "Monitor and Manage Google Cloud Resources",
    "Protect Sensitive Data with Data Loss Prevention",
    "Implement Load Balancing on Compute Engine",
    "Networking Fundamentals on Google Cloud",
    "Build Google Cloud Infrastructure for Azure Professionals",
    "Implement CI/CD Pipelines on Google Cloud",
    "Inspect Rich Documents with Gemini Multimodality and Multimodal RAG",
    "Analyze Speech and Language with Google APIs",
    "Get Started with API Gateway",
    "Prompt Design in Vertex AI",
    "Create and Manage Bigtable Instances",
    "Store, Process, and Manage Data on Google Cloud - Console",
    "Use APIs to Work with Cloud Storage",
    "Integrate BigQuery Data and Google Workspace using Apps Script",
    "Store, Process, and Manage Data on Google Cloud - Command Line",
    "Get Started with Cloud Storage",
    "Manage Kubernetes in Google Cloud",
    "Protect Cloud Traffic with BeyondCorp Enterprise (BCE) Security",
    "Migrate MySQL data to Cloud SQL using Database Migration Service",
    "App Building with AppSheet",
    "Cloud Speech API: 3 Ways",
    "Monitor and Log with Google Cloud Observability",
    "Set Up an App Dev Environment on Google Cloud",
    "Develop GenAI Apps with Gemini and Streamlit",
    "Create a Streaming Data Lake on Cloud Storage",
    "Monitoring in Google Cloud",
    "Build Google Cloud Infrastructure for AWS Professionals",
    "Use Machine Learning APIs on Google Cloud",
    "Build a Data Mesh with Dataplex",
    "Develop your Google Cloud Network",
    "Mitigate Threats and Vulnerabilities with Security Command Center",
    "Configure Service Accounts and IAM Roles for Google Cloud",
    "Create and Manage AlloyDB Instances",
    "Get Started with Looker",
    "Analyze Sentiment with Natural Language API",
    "Implement Cloud Security Fundamentals on Google Cloud",
    "Build LangChain Applications using Vertex AI",
    "Build Infrastructure with Terraform on Google Cloud",
    "Google Workspace for Education",
    "Cloud Run Functions: 3 Ways",
    "Explore Generative AI with the Gemini API in Vertex AI",
    "Analyze BigQuery Data in Connected Sheets",
    "Explore Generative AI with the Vertex AI Gemini API",
    "Enhance Gemini Model Capabilities",
    "Discover and Protect Sensitive Data Across Your Ecosystem",
    "Modernize Java Applications",
    "Implement Multimodal Vector Search with BigQuery",
    "Generative AI Fundamentals",
    "Deploy Agentspace",
    "Extend Agentspace assistant capabilities",
    "Build search and recommendations AI Applications",
    "Build generative virtual agents with API integrations",
    "Create and maintain Vertex AI Search data stores",
    "Build basic Conversational Agents with Playbooks and Flows",
    "Configure AI Applications to optimize search results",
    "Analyze patterns in conversational data with Conversational Insights",
    "Create media search and media recommendations applications with AI Applications",
    "Build deterministic Virtual Agent enhanced with data stores",
    "Deploy, Test & Evaluate Gen AI Apps",
    "Modernize .Net Applications",
    "Build search and recommendations applications with AI Applications",
    "Analyze and Reason on Multimodal Data with Gemini",
]

const specialBadgeList = [
    "Skills Boost Arcade Base Camp February 2025",
    "Skills Boost Arcade Base Camp April 2025",
    "Skills Boost Arcade Base Camp May 2025",
    "Skills Boost Arcade Base Camp June 2025",
    "Skills Boost Arcade Base Camp March 2025",
    "The Arcade Base Camp January 2025",
    "Skills Boost Arcade Certification Zone April 2025",
    "Skills Boost Arcade Certification Zone May 2025",
    "Skills Boost Arcade Certification Zone February 2025",
    "Skills Boost Arcade Certification Zone March 2025",
    "The Arcade Certification Zone January 2025",
    "Level 2: Automation and Performance Testing",
    "Level 1: Application Development and Security with GCP",
    "Level 3: The Arcade Quiz",
    "Level 2: Cloud Infrastructure & API Essentials",
    "Level 1: Data Modeling and Reporting",
    "Level 2: Data Exploration and Integration",
    "Level 3: Building Blocks_",
    "Level 1: Application and Network Infrastructure",
    "Level 3: AI Readiness",
    "Level 2: Security and Monitoring in GCP",
    "Level 1: Security and Data Management with GCP",
    "Level 2: Cloud Deployment and Security",
    "Level 1: App Dev and Deployment",
    "Level 3: Building Blocks",
    "Level 2: Analysis with AI",
    "Level 1: Data Operations and Workflow Optimization",
    "Level 3: Arcade Heroes",
    "Level 3: ACE App Dev",
    "Arcade NetworSkills",
    "Arcade Learn-a-Thon",
    "Arcade TechCare",
    "Skills Boost Arcade Skillsresolve",
    "Color Your Skills",
    "Love Beyond Query!",
    "Skills Boost Arcade Trivia May 2025 Week 2",
    "Skills Boost Arcade Trivia June 2025 Week 4",
    "Skills Boost Arcade Trivia June 2025 Week 3",
    "Skills Boost Arcade Trivia June 2025 Week 2",
    "Skills Boost Arcade Trivia June 2025 Week 1",
    "Skills Boost Arcade Trivia March 2025 Week 4",
    "Skills Boost Arcade Trivia March 2025 Week 3",
    "Skills Boost Arcade Trivia March 2025 Week 2",
    "Skills Boost Arcade Trivia May 2025 Week 4",
    "Skills Boost Arcade Trivia March 2025 Week 1",
    "Skills Boost Arcade Trivia May 2025 Week 3",
    "The Arcade Trivia January 2025 Week 2",
    "Skills Boost Arcade Trivia February 2025 Week 3",
    "Skills Boost Arcade Trivia May 2025 Week 1",
    "Skills Boost Arcade Trivia February 2025 Week 4",
    "The Arcade Trivia January 2025 Week 1",
    "Skills Boost Arcade Trivia February 2025 Week 2",
    "Skills Boost Arcade Trivia April 2025 Week 4",
    "Skills Boost Arcade Trivia February 2025 Week 1",
    "Skills Boost Arcade Trivia April 2025 Week 3",
    "Skills Boost Arcade Trivia January 2025 Week 4",
    "The Arcade Trivia January 2025 Week 3",
    "Skills Boost Arcade Trivia April 2025 Week 2",
    "Skills Boost Arcade Trivia April 2025 Week 1",
]

const labfreeBadges = [
    "Digital Transformation with Google Cloud",
    "Exploring Data Transformation with Google Cloud",
    "Modernize Infrastructure and Applications with Google Cloud",
    "Scaling with Google Cloud Operations",
    "Innovating with Google Cloud Artificial Intelligence",
    "Trust and Security with Google Cloud",
    "Google Drive",
    "Google Docs",
    "Google Slides",
    "Google Meet",
    "Google Sheets",
    "Google Calendar",
    "Responsible AI: Applying AI Principles with Google Cloud",
    "Responsible AI for Digital Leaders with Google Cloud",
    "Customer Engagement Suite with Google AI Architecture",
    "Machine Learning Operations (MLOps) with Vertex AI: Model Evaluation",
    "Conversational AI on Vertex AI and Dialogflow CX",
    "Building Complex End to End Self-Service Experiences in Dialogflow CX",
]


const badges = {
    skillBadges: skillBadgeList,
    specialBadges: specialBadgeList,
    labfreeBadges
}

export default badges